spin_manifest_version = 2

[application]
name = "lipl-storage-spin"
version = "0.10.2"
authors = ["paulusminus <info@paulmin.nl>"]
description = "Lipl Storage on spin"

[[trigger.http]]
route = "/lipl/api/v1/..."
component = "lipl-storage-spin"

[[trigger.http]]
route = "/..."
component = "fileserver"

[variables]
lipl_username = { required = true }
lipl_password = { required = true }

[component.lipl-storage-spin]
source = "target/wasm32-wasip1/release/lipl_storage_spin.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.lipl-storage-spin.variables]
lipl_username = "{{ lipl_username }}"
lipl_password = "{{ lipl_password }}"

[component.lipl-storage-spin.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.lipl-storage-spin.tool.spin-test]
source = "../lipl-storage-test/target/wasm32-wasip1/release/lipl_storage_test.wasm"
build = "cargo component build --release --target=wasm32-wasip1"
workdir = "../lipl-storage-test"
sqlite_databases = ["default"]

[component.lipl-storage-spin.tool.spin-test.variables]
lipl_username = "{{ lipl_username }}"
lipl_password = "{{ lipl_password }}"

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "pwa", destination = "/" }]
